version: '3'
services:
  
  # orchestrator
  orchestrator:
    build: src/
    environment:
      MONGODB_USER: root
      MONGODB_PASS: rootpassword
      MONGODB_HOST: mongo
      MONGODB_PORT: 27017
    ports:
      - 3000:3000
    links: 
      - mongo
  
  # mongo
  mongo:
    image: mongo:4.4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

networks:
  orchestrator: