version: '3'
services:
  
  # orchestrator
  orchestrator:
    build: src/
    environment:
      GENERIC_GATEWAY_HOST: localhost
      GENERIC_GATEWAY_PORT: 8081
      BRIGADE_API_HOST: localhost
      BRIGADE_API_PORT: 7745
      MONGODB_USER: root
      MONGODB_PASS: rootpassword
      MONGODB_HOST: 0.0.0.0
      MONGODB_PORT: 27017
    healthcheck:
      test: ["CMD", "curl", "-f", "mongo:27017"]
      interval: 30s
      timeout: 10s
      retries: 5 
    ports:
      - 3000:3000
    network_mode: host
  
  # mongo
  mongo:
    image: mongo:4.4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

