apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: fireworq
spec:
  selector:
    matchLabels:
      app: fireworq
  replicas: 1
  template:
    metadata:
      labels:
        app: fireworq
    spec:
      containers:
      - name: fireworq
        image: fireworq/fireworq:1.4
        ports:
          - containerPort: 8080
        env:
          - name: "FIREWORQ_DRIVER"
            value: "in-memory"
          - name: "FIREWORQ_QUEUE_DEFAULT"
            value: "default"

---

apiVersion: v1
kind: Service
metadata:
  name: fireworq
  labels:
    app: fireworq
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: fireworq