apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: orchestrator
spec:
  selector:
    matchLabels:
      app: orchestrator
  replicas: 1
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - name: orchestrator
        image: {{ .Values.orchestrator.image }}
        imagePullPolicy: IfNotPresent
        env:
          - name: BRIGADE_HOST
            value: {{ .Values.orchestrator.environment  }}-brigade-generic-gateway 
          - name: BRIGADE_PORT
            value: "8081"
          - name: MONGODB_USER
            value: root
          - name: MONGODB_PASS
            value: rootpassword
          - name: MONGODB_HOST
            value: {{ .Values.orchestrator.environment  }}-mongodb
          - name: MONGODB_PORT
            value: "27017"
        ports:
          - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  labels:
    app: orchestrator
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: orchestrator